# Generated by Django 5.2.7 on 2025-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_app", "0002_alter_dish_cooks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dish_ingredients", to="kitchen_app.ingredient"
            ),
        ),
    ]
